### ISSUE TITLE
Export to GHA cache fails with an error

### ISSUE THREAD

**Issue by tlinhart** [pulumi/pulumi-docker-build#77]
### What happened?

I'm trying to build a Docker image using the new Docker Build provider while employing the GitHub Actions cache as per the [documentation](https://www.pulumi.com/registry/packages/docker-build/api-docs/image/). The Pulumi program runs in a GHA workflow job as outlined below. However, exporting the cache fails with an error.

### Example

This is the relevant part of the Pulumi program:

```
image_name = pulumi.Output.concat(repository.repository_url, ":latest")
if os.getenv("GITHUB_ACTIONS"):
    cache_from = docker_build.CacheFromArgs(
        gha=docker_build.CacheFromGitHubActionsArgs()
    )
    cache_to = docker_build.CacheToArgs(
        gha=docker_build.CacheToGitHubActionsArgs(
            mode=docker_build.CacheMode.MAX, ignore_error=True
        )
    )
else:
    cache_from = docker_build.CacheFromArgs(
        registry=docker_build.CacheFromRegistryArgs(ref=image_name)
    )
    cache_to = docker_build.CacheToArgs(
        inline=docker_build.CacheToInlineArgs()
    )
image = docker_build.Image(
    "xxx",
    context=docker_build.BuildContextArgs(location=".."),
    platforms=[docker_build.Platform.LINUX_AMD64],
    tags=[image_name],
    cache_from=[cache_from],
    cache_to=[cache_to],
    push=True,
    registries=[
        docker_build.RegistryArgs(
            address=repository.repository_url,
            username=auth_token.user_name,
            password=pulumi.Output.secret(auth_token.password),
        )
    ],
)
```

This is the relevant part of the GitHub Actions workflow:

```
name: CI
on:
  push:
    branches:
      - "**"
permissions:
  contents: read
  id-token: write
jobs:
  infra:
    name: Provision infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
      - name: Create or update stack resources
        uses: pulumi/actions@v5
        with:
          command: up
          refresh: true
          diff: true
          suppress-progress: true
          stack-name: xxx-prod
          work-dir: infra
          cloud-url: s3://xxx
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
```

This is the relevant part of the GitHub Actions log from the `pulumi up` step:

```
  #51 [auth] sharing credentials for xxx.dkr.ecr.eu-central-1.amazonaws.com
  #51 DONE 0.0s
  #50 exporting to image
  #50 pushing layers 6.9s done
  #50 pushing manifest for xxx.dkr.ecr.eu-central-1.amazonaws.com/xxx-ac3cfb0:latest@sha256:xxx
  #50 pushing manifest for xxx.dkr.ecr.eu-central-1.amazonaws.com/xxx-ac3cfb0:latest@sha256:xxx 0.6s done
  #50 DONE 17.0s
  #52 exporting to GitHub Actions Cache
  #52 preparing build cache for export
  #52 preparing build cache for export 19.5s done
  #52 ERROR: failed to parse error response 404: : unexpected end of JSON input
```

### Output of `pulumi about`

```
CLI          
Version      3.116.1
Go Version   go1.22.2
Go Compiler  gc

Host     
OS       ubuntu
Version  24.04
Arch     x86_64

Backend        
Name           xxx
URL            s3://xxx
User           xxx
Organizations  
Token type     personal

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
